In [8]:
list_of_countries = ['Algeria','Angola','Argentina','Australia','Austria','Bahamas','Bangladesh','Belarus','Belgium','Bhutan','Brazil','Bulgaria','Cambodia','Cameroon','Chile','China','Colombia','Cyprus','Denmark','El Salvador','Estonia','Ethiopia','Fiji','Finland','France','Georgia','Ghana','Grenada','Guinea','Haiti','Honduras','Hungary','India','Indonesia','Ireland','Italy','Japan','Kenya', 'South Korea','Liberia','Malaysia','Mexico', 'Morocco','Nepal','New Zealand','Norway','Pakistan', 'Peru','Qatar','Russia','Singapore','South Africa','Spain','Sweden','Switzerland','Thailand', 'United Arab Emirates','United Kingdom','United States','Uruguay','Venezuela','Vietnam','Zimbabwe']

In [9]:
gdp_values_for_each_countries = [2255.225482,629.9553062,11601.63022,25306.82494,27266.40335,19466.99052,588.3691778,2890.345675,24733.62696,1445.760002,4803.398244,2618.876037,590.4521124,665.7982328,7122.938458,2639.54156,3362.4656,15378.16704,30860.12808,2579.115607,6525.541272,229.6769525,2242.689259,27570.4852,23016.84778,1334.646773,402.6953275,6047.200797,394.1156638,385.5793827,1414.072488,5745.981529,837.7464011,1206.991065,27715.52837,18937.24998,39578.07441,478.2194906,16684.21278,279.2204061,5345.213415,6288.25324,1908.304416,274.8728621,14646.42094,40034.85063,672.1547506,3359.517402,36152.66676,3054.727742,33529.83052,3825.093781,15428.32098,33630.24604,39170.41371,2699.123242,21058.43643,28272.40661,37691.02733,9581.05659,5671.912202,757.4009286,347.7456605]

In [14]:
import numpy as np

In [15]:
list_of_countries = np.array(list_of_countries)

In [16]:
list_of_countries

array(['Algeria', 'Angola', 'Argentina', 'Australia', 'Austria',
       'Bahamas', 'Bangladesh', 'Belarus', 'Belgium', 'Bhutan', 'Brazil',
       'Bulgaria', 'Cambodia', 'Cameroon', 'Chile', 'China', 'Colombia',
       'Cyprus', 'Denmark', 'El Salvador', 'Estonia', 'Ethiopia', 'Fiji',
       'Finland', 'France', 'Georgia', 'Ghana', 'Grenada', 'Guinea',
       'Haiti', 'Honduras', 'Hungary', 'India', 'Indonesia', 'Ireland',
       'Italy', 'Japan', 'Kenya', 'South Korea', 'Liberia', 'Malaysia',
       'Mexico', 'Morocco', 'Nepal', 'New Zealand', 'Norway', 'Pakistan',
       'Peru', 'Qatar', 'Russia', 'Singapore', 'South Africa', 'Spain',
       'Sweden', 'Switzerland', 'Thailand', 'United Arab Emirates',
       'United Kingdom', 'United States', 'Uruguay', 'Venezuela',
       'Vietnam', 'Zimbabwe'], dtype='<U20')

In [17]:
gdp_values_for_each_countries = np.array(gdp_values_for_each_countries)

In [18]:
gdp_values_for_each_countries


array([ 2255.225482 ,   629.9553062, 11601.63022  , 25306.82494  ,
       27266.40335  , 19466.99052  ,   588.3691778,  2890.345675 ,
       24733.62696  ,  1445.760002 ,  4803.398244 ,  2618.876037 ,
         590.4521124,   665.7982328,  7122.938458 ,  2639.54156  ,
        3362.4656   , 15378.16704  , 30860.12808  ,  2579.115607 ,
        6525.541272 ,   229.6769525,  2242.689259 , 27570.4852   ,
       23016.84778  ,  1334.646773 ,   402.6953275,  6047.200797 ,
         394.1156638,   385.5793827,  1414.072488 ,  5745.981529 ,
         837.7464011,  1206.991065 , 27715.52837  , 18937.24998  ,
       39578.07441  ,   478.2194906, 16684.21278  ,   279.2204061,
        5345.213415 ,  6288.25324  ,  1908.304416 ,   274.8728621,
       14646.42094  , 40034.85063  ,   672.1547506,  3359.517402 ,
       36152.66676  ,  3054.727742 , 33529.83052  ,  3825.093781 ,
       15428.32098  , 33630.24604  , 39170.41371  ,  2699.123242 ,
       21058.43643  , 28272.40661  , 37691.02733  ,  9581.0565

In [19]:
gdp_values_for_each_countries[gdp_values_for_each_countries ==40034.85063]

array([40034.85063])

In [22]:
np.max(gdp_values_for_each_countries)

40034.85063

In [23]:
np.where(gdp_values_for_each_countries ==40034.85063 )

(array([45], dtype=int64),)

In [24]:
gdp_values_for_each_countries[45]

40034.85063

In [27]:
list_of_countries_gdp_values_for_each_countries = np.stack((list_of_countries, gdp_values_for_each_countries))

In [28]:
list_of_countries_gdp_values_for_each_countries

array([['Algeria', 'Angola', 'Argentina', 'Australia', 'Austria',
        'Bahamas', 'Bangladesh', 'Belarus', 'Belgium', 'Bhutan',
        'Brazil', 'Bulgaria', 'Cambodia', 'Cameroon', 'Chile', 'China',
        'Colombia', 'Cyprus', 'Denmark', 'El Salvador', 'Estonia',
        'Ethiopia', 'Fiji', 'Finland', 'France', 'Georgia', 'Ghana',
        'Grenada', 'Guinea', 'Haiti', 'Honduras', 'Hungary', 'India',
        'Indonesia', 'Ireland', 'Italy', 'Japan', 'Kenya', 'South Korea',
        'Liberia', 'Malaysia', 'Mexico', 'Morocco', 'Nepal',
        'New Zealand', 'Norway', 'Pakistan', 'Peru', 'Qatar', 'Russia',
        'Singapore', 'South Africa', 'Spain', 'Sweden', 'Switzerland',
        'Thailand', 'United Arab Emirates', 'United Kingdom',
        'United States', 'Uruguay', 'Venezuela', 'Vietnam', 'Zimbabwe'],
       ['2255.225482', '629.9553062', '11601.63022', '25306.82494',
        '27266.40335', '19466.99052', '588.3691778', '2890.345675',
        '24733.62696', '1445.760002', '480

In [31]:
list_of_countries_gdp_values_for_each_countries.size

126

In [48]:
#Find and print the name of the country with the highest GDP
gdp_values_for_each_countries[gdp_values_for_each_countries ==40034.85063]
np.where(gdp_values_for_each_countries ==40034.85063 )
list_of_countries_gdp_values_for_each_countries = np.stack((list_of_countries, gdp_values_for_each_countries))
name_of_the_country_with_the_highest_GDP = list_of_countries_gdp_values_for_each_countries[:,45]
print(name_of_the_country_with_the_highest_GDP)


['Norway' '40034.85063']


In [36]:
country_with_lowest_gdp_value = np.min(gdp_values_for_each_countries)

In [37]:
country_with_lowest_gdp_value

229.6769525

In [38]:
index_of_country_with_lowest_gdp = np.where(country_with_lowest_gdp_value == 229.6769525)

In [39]:
index_of_country_with_lowest_gdp

(array([0], dtype=int64),)

In [40]:
name_of_the_country_with_the_lowest_GDP = list_of_countries_gdp_values_for_each_countries[:,0]

In [49]:
#Find and print the name of the country with the lowest GDP
country_with_lowest_gdp_value = np.min(gdp_values_for_each_countries)
index_of_country_with_lowest_gdp = np.where(country_with_lowest_gdp_value == 229.6769525)
index_of_country_with_lowest_gdp

print(name_of_the_country_with_the_lowest_GDP)

['Algeria' '2255.225482']


In [44]:
#Print out text and input values iteratively
for element in list_of_countries_gdp_values_for_each_countries:
    print(element)

['Algeria' 'Angola' 'Argentina' 'Australia' 'Austria' 'Bahamas'
 'Bangladesh' 'Belarus' 'Belgium' 'Bhutan' 'Brazil' 'Bulgaria' 'Cambodia'
 'Cameroon' 'Chile' 'China' 'Colombia' 'Cyprus' 'Denmark' 'El Salvador'
 'Estonia' 'Ethiopia' 'Fiji' 'Finland' 'France' 'Georgia' 'Ghana'
 'Grenada' 'Guinea' 'Haiti' 'Honduras' 'Hungary' 'India' 'Indonesia'
 'Ireland' 'Italy' 'Japan' 'Kenya' 'South Korea' 'Liberia' 'Malaysia'
 'Mexico' 'Morocco' 'Nepal' 'New Zealand' 'Norway' 'Pakistan' 'Peru'
 'Qatar' 'Russia' 'Singapore' 'South Africa' 'Spain' 'Sweden'
 'Switzerland' 'Thailand' 'United Arab Emirates' 'United Kingdom'
 'United States' 'Uruguay' 'Venezuela' 'Vietnam' 'Zimbabwe']
['2255.225482' '629.9553062' '11601.63022' '25306.82494' '27266.40335'
 '19466.99052' '588.3691778' '2890.345675' '24733.62696' '1445.760002'
 '4803.398244' '2618.876037' '590.4521124' '665.7982328' '7122.938458'
 '2639.54156' '3362.4656' '15378.16704' '30860.12808' '2579.115607'
 '6525.541272' '229.6769525' '2242.689259' '27

In [46]:
#Print out the entire list of the countries with their GDPs
list_of_countries_gdp_values_for_each_countries = np.stack((list_of_countries, gdp_values_for_each_countries))
print(list_of_countries_gdp_values_for_each_countries)


[['Algeria' 'Angola' 'Argentina' 'Australia' 'Austria' 'Bahamas'
  'Bangladesh' 'Belarus' 'Belgium' 'Bhutan' 'Brazil' 'Bulgaria'
  'Cambodia' 'Cameroon' 'Chile' 'China' 'Colombia' 'Cyprus' 'Denmark'
  'El Salvador' 'Estonia' 'Ethiopia' 'Fiji' 'Finland' 'France' 'Georgia'
  'Ghana' 'Grenada' 'Guinea' 'Haiti' 'Honduras' 'Hungary' 'India'
  'Indonesia' 'Ireland' 'Italy' 'Japan' 'Kenya' 'South Korea' 'Liberia'
  'Malaysia' 'Mexico' 'Morocco' 'Nepal' 'New Zealand' 'Norway' 'Pakistan'
  'Peru' 'Qatar' 'Russia' 'Singapore' 'South Africa' 'Spain' 'Sweden'
  'Switzerland' 'Thailand' 'United Arab Emirates' 'United Kingdom'
  'United States' 'Uruguay' 'Venezuela' 'Vietnam' 'Zimbabwe']
 ['2255.225482' '629.9553062' '11601.63022' '25306.82494' '27266.40335'
  '19466.99052' '588.3691778' '2890.345675' '24733.62696' '1445.760002'
  '4803.398244' '2618.876037' '590.4521124' '665.7982328' '7122.938458'
  '2639.54156' '3362.4656' '15378.16704' '30860.12808' '2579.115607'
  '6525.541272' '229.6769525' '2

In [47]:
#Print the highest GDP value, lowest GDP value, mean GDP value, standardized GDP value, and the sum of all the GDPs
print(name_of_the_country_with_the_highest_GDP[1],name_of_the_country_with_the_lowest_GDP[1],np.mean(gdp_values_for_each_countries),np.std(gdp_values_for_each_countries),np.sum(gdp_values_for_each_countries))

40034.85063 2255.225482 11289.409271639683 12743.828910617945 711232.7841133
